apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: default
type: Opaque
stringData:
  smtp-username: "your-email@gmail.com"
  smtp-password: "your-app-specific-password"
  from-email: "your-email@gmail.com"
  to-emails: "recipient1@example.com,recipient2@example.com,team@example.com"  # Comma-separated list of recipients 