apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: default
type: Opaque
stringData:
  smtp-host: "smtp.localhost"
  smtp-port: "587"
  use-auth: "false"
  smtp-username: "test"
  smtp-password: "test"
  from-email: "test@example.com"
  to-emails: "test@example.com"
