apiVersion: v1
kind: Service
metadata:
  name: resource-watcher
  namespace: default
  labels:
    app: resource-watcher
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: resource-watcher
 